<p style='text-align:center'>
PSY 394U <b>Methods for fMRI</b>, Fall 2018


<img style='width: 300px; padding: 0px;' src='https://github.com/sathayas/JupyterfMRIFall2018/blob/master/Images/Placebo_Left.png?raw=true' alt='brain blobs'/>

</p>

<p style='text-align:center; font-size:40px; margin-bottom: 30px;'><b>Basics of Python coding</b></p>

<p style='text-align:center; font-size:18px; margin-bottom: 32px;'><b>September 10 - 17, 2018</b></p>

<hr style='height:5px;border:none' />

# Essential Unix commands
<hr style="height:1px;border:none" />

Before we get started with Python coding, I thought it is a good idea to learn a few essential Unix commands. Many coding tools and some software tools for neuroimaging can be interfaced by using Unix commands from a terminal. Although Unix is completely replaced by Linux, you can still use essential Unix commands on Linux and Mac OS to accomplish various operations (copying files, moving files, creating directories, etc.). So knowing a few Unix commands can be a useful asset.

For this exercise, please open a terminal (for Mac and Linux users). 

*If you are using a **Windows** computer, I highly recommend installing a Unix-like virtual machine (VM) on your computer. There is a distribution of VM called FSLvm from FSL (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation/Windows). You can follow its installation instructions.*

## `ls` command
You can type a command
```
ls -l
```
and you will see a detailed list of items (files & directories) under your current directory. For example,
```
PSYC-A06168:~ sh45474$ ls -l
total 0
drwxrwxr-x@  3 sh45474  2066930642   102 Oct 10  2016 Creative Cloud Files
drwx------+  4 sh45474  2066930642   136 Jun 29 14:23 Desktop
drwx------+ 11 sh45474  2066930642   374 Dec  4  2017 Documents
drwx------+ 11 sh45474  2066930642   374 Jul  2 22:31 Downloads
drwx------@ 61 sh45474  2066930642  2074 Sep 14  2017 Library
drwx------+  3 sh45474  2066930642   102 Mar 23  2016 Movies
drwx------+  4 sh45474  2066930642   136 Apr  1  2016 Music
drwx------+  7 sh45474  2066930642   238 Aug 19  2016 Pictures
drwxr-xr-x+  5 sh45474  2066930642   170 Mar 23  2016 Public
drwxr-xr-x   5 sh45474  2066930642   170 Mar 14  2017 SoftwareTools
drwxr-xr-x   9 sh45474  2066930642   306 Apr 11 12:27 nltk_data
drwxr-xr-x   3 sh45474  2066930642   102 Apr 25 21:42 scikit_learn_data
```

On this list, directories are denoted by **`d`** at the first character, whereas files are denoted by **`-`**.  Or, you can run **`ls`** command on its own, which gives just a list without details.
```
PSYC-A06168:~ sh45474$ ls
Creative Cloud Files	Library			Public
Desktop			Movies			SoftwareTools
Documents		Music			nltk_data
Downloads		Pictures		scikit_learn_data
```

You can also run the `ls` command from a Jupyter notebook document. To do so, you have to type an exclamation mark (**`!`**) before the command (indicating that this is a Unix shell command, as opposed to a Python command).

In [1]:
!ls -l ~

total 0
drwxrwxr-x@  3 sh45474  2066930642   102 Oct 10  2016 Creative Cloud Files
drwx------+  4 sh45474  2066930642   136 Jun 29 14:23 Desktop
drwx------+ 11 sh45474  2066930642   374 Dec  4  2017 Documents
drwx------+ 11 sh45474  2066930642   374 Jul  2 22:31 Downloads
drwx------@ 61 sh45474  2066930642  2074 Sep 14  2017 Library
drwx------+  3 sh45474  2066930642   102 Mar 23  2016 Movies
drwx------+  4 sh45474  2066930642   136 Apr  1  2016 Music
drwx------+  7 sh45474  2066930642   238 Aug 19  2016 Pictures
drwxr-xr-x+  5 sh45474  2066930642   170 Mar 23  2016 Public
drwxr-xr-x   5 sh45474  2066930642   170 Mar 14  2017 SoftwareTools
drwxr-xr-x   9 sh45474  2066930642   306 Apr 11 12:27 nltk_data
drwxr-xr-x   3 sh45474  2066930642   102 Apr 25 21:42 scikit_learn_data


Here I put a tilde (**`~`**) after `ls -l`. This is a shorthand notation of your home directory. If you run `ls -l` on Jupyter without a tilde, you will be a print out of the content of where your Jupyter notebook document is stored.

In [2]:
!ls -l

total 72
-rw-r--r--   1 sh45474  2066930642   5731 Jul 12 13:25 BasicPython.ipynb
drwxr-xr-x  15 sh45474  2066930642    510 Jul 11 15:46 Images
-rw-r--r--   1 sh45474  2066930642  23219 Jul 12 12:57 Intro.ipynb
-rw-r--r--   1 sh45474  2066930642    204 Jul 11 16:09 README.md


## `mkdir` command
You can create a directory with the **`mkdir`** command, followed by the name of the directory. Say, I want to create a directory called **`fMRI_stuff`** under my home directory, I can type
```
mkdir fMRI_stuff
```
Just to verify whether it was actually created, I run `ls -l` again.
```
PSYC-A06168:~ sh45474$ ls -l
total 0
drwxrwxr-x@  3 sh45474  2066930642   102 Oct 10  2016 Creative Cloud Files
drwx------+  4 sh45474  2066930642   136 Jun 29 14:23 Desktop
drwx------+ 11 sh45474  2066930642   374 Dec  4  2017 Documents
drwx------+ 11 sh45474  2066930642   374 Jul  2 22:31 Downloads
drwx------@ 61 sh45474  2066930642  2074 Sep 14  2017 Library
drwx------+  3 sh45474  2066930642   102 Mar 23  2016 Movies
drwx------+  4 sh45474  2066930642   136 Apr  1  2016 Music
drwx------+  7 sh45474  2066930642   238 Aug 19  2016 Pictures
drwxr-xr-x+  5 sh45474  2066930642   170 Mar 23  2016 Public
drwxr-xr-x   5 sh45474  2066930642   170 Mar 14  2017 SoftwareTools
drwxr-xr-x   2 sh45474  2066930642    68 Jul 12 13:32 fMRI_stuff
drwxr-xr-x   9 sh45474  2066930642   306 Apr 11 12:27 nltk_data
drwxr-xr-x   3 sh45474  2066930642   102 Apr 25 21:42 scikit_learn_data
```

And you can see it's there.

## `cd` command
To move from one directory to another, you can use the **`cd`** command. Its syntax is
```
cd [directory name]
```
where `[directory name]` is the location you want to move. We can move to the `fMRI_stuff` directory we created earlier by
```
cd fMRI_stuff
```
To verify if you are really there, you can use the **`pwd`** command you saw earlier.
```
PSYC-A06168:fMRI_stuff sh45474$ pwd
/Users/sh45474/fMRI_stuff
```


Note that your result is likely different from mine.

Now let's create a directory called **`Data`**, and under `Data`, let's create a directory called **`func`**.
```
mkdir Data
cd Data
mkdir func
```
Then let's move to `func`. 
```
cd func
```
The current directory is 
```
PSYC-A06168:func sh45474$ pwd
/Users/sh45474/fMRI_stuff/Data/func
```

At this point you can go back to `fMRI_stuff` (two directories above) by
```
cd ..
cd ..
```
or 
```
cd ../..
```
Here, double periods indicate one directory above.
```
PSYC-A06168:fMRI_stuff sh45474$ pwd
/Users/sh45474/fMRI_stuff
```

Let's say, you want to go back to `func` directory. You can do
```
cd Data/func
```
This way of addressing the directory is called a **relative path**, originating from the  directory you are currently in.

You can also go to the same directory by
```
cd /Users/sh45474/fMRI_stuff/Data/func
```
This way of addressing the directory is called an **absolute path**. This command works whichever directory you are currently in

The **path** is the address for a directory or a file. It can be relative or absolute.


## Other useful commands

There are other useful Unix commands. I will to over them whenever we use one of these.
<table>
<tr>
<th style="text-align:left">Command</th>
<th style="text-align:left">What it does</th>
<th style="text-align:left">Syntax</th>
</tr>
<tr>
<td style="text-align:left">cat</td><td style="text-align:left">Prints a text file on a screen</td><td style="text-align:left">cat [file name]</td>
</tr>
<tr>
<td style="text-align:left">cp</td><td style="text-align:left">Copies a file or a directory</td><td style="text-align:left">cp [original item] [copied item]</td>
</tr>
<tr>
<td style="text-align:left">gzip</td><td style="text-align:left">Compresses a file (.gz added)</td><td style="text-align:left">gzip [file]</td>
</tr>
<tr>
<td style="text-align:left">gzip -d </td><td style="text-align:left">Uncompresses a file (.gz removed)</td><td style="text-align:left">gzip -d [file].gz</td>
</tr>

<tr>
<td style="text-align:left">more</td><td style="text-align:left">Prints a text file on a screen (pagenated version)</td><td style="text-align:left">more [file name]</td>
</tr>
<tr>
<td style="text-align:left">mv</td><td style="text-align:left">Moves a file or a directory</td><td style="text-align:left">mv [origin] [target]</td>
</tr>
<tr>
<td style="text-align:left">rm</td><td style="text-align:left">Deletes a file</td><td style="text-align:left">rm [file name]</td>
</tr>
<tr>
<td style="text-align:left">rmdir</td><td style="text-align:left">Deletes a directory</td><td style="text-align:left">rmdir [directory name]</td>
</tr>
</table>



# Operators
<hr style="height:1px;border:none" />

## Math operators
In your Python shell, try typing the following.


In [5]:
2 + 2

4

This is a simple example of an expression. An expression is an instruction consisting of numbers (e.g., 2) and mathematical operators (e.g. +). Any space in an expression is ignored. In addition to (no pun intended) addition (`+`), there are other operators:

  * Addition: `+`
  * Subtraction: `-`
  * Multiplication: `*`
  * Integer division: `//`
  * Division: `/`
  * Remainder after division: `%`
  * Exponent: `**`
  
## Application

### Scenario 1
Now consider the following scenario. You bought lunch for 3 of your friends and yourself. Each person had a sandwich (\$6.50) and a soda (\$1.50). How much in total did you pay?

In this scenario, you pay \$6.50 + \$1.50 per person. Since there are 4 of you, you paid

In [6]:
(6.50+1.50)*4

32.0

### Scenario 2
Your fMRI experiment consists of 10 epochs of finger tapping (25s), and each epoch followed by 25s of rest. Before the first epoch, there is 15s of rest. What is the total duration of this experiment (in s)?

In [7]:
15 + 10*(25 + 25)

515

### Scenario 3
If you have \$20, how many sodas (\$1.50 each) can you buy on a vending machine?

In [8]:
20 // 1.50

13.0

And what would be the remainder after you buy that many sodas?

In [10]:
20 % 1.50

0.5

### Exercise
1. **How many scans**. Say, you are given a pilot grant of \$3,000 to scan subjects on an MRI scanner. You will be charged \$435 for the MRI scan for each subject. How many subjects can you scan with your pilot grant? (Post the solution formula on Canvas)
2. **How many stimuli**. You are designing an experiment with two conditions: listening to a story in English (Condition 1) and in Spanish (Condition 2). Each condition is 15s long, and has to be followed by 25s of silence. Your experiment has to have the same number of both conditions, and has to be under 10 minutes. How many Conditions 1 and 2 can you include in your experiment? (Post the solution formula on Canvas)

## String operators
In addition to numerical data, Python can also handle text data, also known as strings. A string is a series of characters (including space), and often denoted with quotation marks (') or (").

In [13]:
'Hello!'

'Hello!'

If you forget quotation marks, then you will likely get an error message

In [14]:
Hello

NameError: name 'Hello' is not defined

These are examples of strings:
```python
'a', 'AA', 'Aaaargh!', 'Hello World!', '24', '24 x 7'
```

As you have already seen before, you can concatenate two strings with `+`. For example,


In [15]:
'Maroon' + '5'

'Maroon5'

You can also repeat string data with `*`. For example,

In [16]:
'Yum! ' * 3

'Yum! Yum! Yum! '

# Variables and lists
<hr style="height:1px;border:none" />

## Variables
When you write a program, it is easier to store your numerical and string data to variables. A variable can be considered as a box where you store your data. For example,


In [18]:
age = 23

This statement puts 23 into a variable called **`age`**. If you type the variable name, then you can see what's in it

In [19]:
age

23

You can store a string into a variable. For example, in the variable called **`name`**,

In [20]:
name = 'Hayasaka'

In [21]:
name

'Hayasaka'

You can use variables in numerical and string operations. For example,

In [22]:
age + 5

28

In [23]:
'My name is ' + name

'My name is Hayasaka'

You can update a variable by replacing its value. For example,

In [24]:
name = 'Hnason'

In [25]:
name

'Hnason'

In [26]:
age = 55

In [27]:
age

55

You can name a variable anyway you like, as long as you follow some simple rules.

  1. Variable names can contain only alphabets, numbers, and underscore (`_`).
  2. Variable names cannot start with a number.
  3. Variable names cannot contain a space
  4. Variable names are case sensitive. For example, **`Name`** and **`name`** are two different variables.
  5. You cannot use certain keywords reserved for Python.

|        |      |       |      |        |
|:--:    |:--:  |:--:   |:--:  |:--:    |
|and     |del   |finally|in    |print   |
|assert  |elif  |for    |is    |raise   |
|break   |else  |from   |lambda|return  |
|class   |except|global |not   |try     |
|continue|exec  |if     |or    |True    |
|def     |False |import |pass  |while   |
|        |      |       |      |yield   |
|        |      |       |      |        |

## Converting strings to numbers

You can convert a string to a number, if it consists of numbers. For example,

In [37]:
numApple = input("How many apples would you like ($1.25 each)? ")

How many apples would you like ($1.25 each)? 4


In this case, the variable **`numApple`** is a string.

In [38]:
numApple

'4'

Consequently, you will get an error if you do this:

In [39]:
total = 1.25 * numApple

TypeError: can't multiply sequence by non-int of type 'float'

You can avoid this by using the **`int()`** function to convert a numerical string into a number.

In [42]:
total = 1.25 * int(numApple)
total

5.0

You can also convert a number into a string variable by **`str()`** function. For example,

In [45]:
age = 23

In [47]:
print("I am " + str(age) + " years old.")

I am 23 years old.


You need to use the `str()` function. Otherwise you get an error.

In [48]:
print("I am " + age + " years old.")

TypeError: must be str, not int

## Lists

A list is like a collection of variables. A collection of numbers and/or strings can be stored in a list. Here are examples of lists:

In [28]:
memberNames = ['Paul', 'John', 'George', 'Ringo']

In [29]:
memberNames

['Paul', 'John', 'George', 'Ringo']

In [30]:
numberList = [1, 5, 23, 512, 1023.5]

In [31]:
numberList

[1, 5, 23, 512, 1023.5]

As you can see, a list is bounded by square brackets `[]`, with elements separated by commas (`,`). To access an individual item of a list, you can use an index inside square brackets. For example,

In [32]:
memberNames = ['Paul', 'John', 'George', 'Ringo', 'Yoko']

In [33]:
memberNames[0]

'Paul'

In [34]:
memberNames[4]

'Yoko'

Notice that the indices start from 0 (referring to the first item on the list) and end with 4 (or, the number of items minus 1). You can use the **`len()`** function to figure out how many items are in a list.

In [35]:
len(memberNames)

5

In Python, you can also use a negative index to access individual items on a list. A negative index starts from -1, the last item on the list.

In [51]:
fruits = ['apple', 'orange', 'banana', 'pineapple']

In [52]:
fruits[-1]

'pineapple'

In [53]:
fruits[-4]

'apple'

## Slicing
## Strings are like lists

# Conditions
<hr style="height:1px;border:none" />

# `while` and `for` loops
<hr style="height:1px;border:none" />

# Functions
<hr style="height:1px;border:none" />

# Arrays
<hr style="height:1px;border:none" />

# Image data
<hr style="height:1px;border:none" />