<p style='text-align:center'>
PSY 394U <b>Methods for fMRI</b>, Fall 2018


<img style='width: 300px; padding: 0px;' src='https://github.com/sathayas/JupyterfMRIFall2018/blob/master/Images/Placebo_Left.png?raw=true' alt='brain blobs'/>

</p>

<p style='text-align:center; font-size:40px; margin-bottom: 30px;'><b>NumPy arrays, image data</b></p>

<p style='text-align:center; font-size:18px; margin-bottom: 32px;'><b>September 17, 2018</b></p>

<hr style='height:5px;border:none' />

# NumPy arrays
<hr style="height:1px;border:none" />

## Creating an array
An array is a data type available in **`NumPy`**. It is similar to a list, but much more
versatile than a list, and especially useful for scientific data.

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a

Note that when we import **`numpy`**, we assign a name **`np`**, so that we don't have to
type `numpy` every time we call a function in the `numpy` module. An array can be
converted to a list, or vice versa.

In [ ]:
list(a)

In [ ]:
b = [10, 9, 8, 7, 6]
np.array(b)

An array can be two dimensional. For example,

In [ ]:
c = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
c

You can examine the shape of an array using the **`ndim`** method (to examine
dimension), the **`shape`** method (to examine the size in each dimension), and the
**`size`** method (to examine the total number of elements).

In [ ]:
c.ndim

In [ ]:
c.shape

In [ ]:
c.size

This tells us that the array `c` is two-dimensional, with 4 rows and 3 columns, and
has 12 elements.

In practice, you usually do not enter elements one by one. Here are some useful
functions. First an array of ones with **`np.ones()`** function.

In [ ]:
np.ones((3,3))

And an array of zeros with **`np.zeros()`** function.

In [ ]:
np.zeros((4,5))

You can change the shape of an array with the **`reshape()`** method. An array of 15 numbers are reshaped into different 2D arrays.

In [ ]:
a = np.arange(15)
a

In [ ]:
b = a.reshape(3,5)
b

## Working with an array

Unlike lists, arrays can be used in mathematical operations. For example,

In [ ]:
a = np.ones((3,3))
a

In [ ]:
b = np.ones((3,3))
b = np.arange(9).reshape(3,3)
b

In [ ]:
a + b

In [ ]:
a * b

An operation involving arrays is performed on element-by-element basis. You can also perform an operation between an array and a scalar (i.e., a single number). In such a case, each element in the array is used in an operation with a scalar.

In [ ]:
a + 10

In [ ]:
5 * a

Of course, you can perform a matrix-like operations as well. First, you can transpose a matrix with **`T`**. 

In [ ]:
B = np.array([[1,2,3],[3,2,2],[0,1,1]])
B

In [ ]:
B.T

Here is a matrix multiplication by the **`np.dot()`**.

In [ ]:
V = np.arange(1,4).reshape(3,1)
V

In [ ]:
np.dot(B,V)

And finally the inverse matrix by the **`np.linalg.inv()`** function. 

In [ ]:
invB = np.linalg.inv(B)
invB

In [ ]:
np.dot(invB,B)

## Useful methods

Here are some useful methods for arrays. First, finding the maximum with the **`max`** method. You can find the maximum for the entire array.

In [ ]:
a = np.random.rand(4,3)
a

In [ ]:
a.max()

Or for each row

In [ ]:
a.max(axis=1)

Or for each column

In [ ]:
a.max(axis=0)

Similarly, you can use the **`min`** method to find the minimums.

In [ ]:
a.min()

In [ ]:
a.min(axis=1)

In [ ]:
a.min(axis=0)

And you can calculate the sum of an array with the **`sum`** method.

In [ ]:
a.sum()

In [ ]:
a.sum(axis=1)

In [ ]:
a.sum(axis=0)

## Indexing and slicing

You can index and slice an array just the same way as a list.

In [ ]:
x = np.arange(10)**2
x

In [ ]:
x[4]

In [ ]:
x[4:]

In [ ]:
x[-3:]

Unlike a list, you can also have a list of indices to access elements as well.

In [ ]:
x[[1,3,7,8]]

In [ ]:
x[[1,1,1,9]]

For a 2D array, the first index corresponds to the row, and the second index
corresponds to the column. If you ignore the second index, then the entire row is
returned. Both row and column indices can be a number (i.e., index) or a slice.

In [ ]:
b = np.arange(15).reshape(3,5)
b

In [ ]:
b[1]

In [ ]:
b[2,3]

In [ ]:
b[1:,3:]

And, you can use a list for row indices or column indices as well.

In [ ]:
b[1:,[1,1,3,3,2]]

In [ ]:
b[[1,1,0],2:]

In [ ]:
b[[0,1,0,2,1],[1,1,3,3,2]]

## Conditional indexing

With an array, it is easy to generate a sub-array satisfying certain conditions. For
example, lets say you have the following data.

`<ExampleData.py>`

In [ ]:
import numpy as np

subjID = np.array(['sub001']*3 + ['sub005']*4 + ['sub010']*3)
RT = np.array([ 98,  96,  86,  90,  95,  80, 117,  90, 114, 113])
score = np.array([0, 0, 1, 0, 1, 0, 0, 0, 1, 0])

print('ID\tRT\tScore')
for i,iID in enumerate(subjID):
    print(iID, RT[i], score[i], sep='\t')

Then you can create sub-arrays based on a particular subject ID.

In [ ]:
subjID[subjID=='sub005']

In [ ]:
RT[subjID=='sub005']

In [ ]:
score[subjID=='sub005']

You can use technique on 2D arrays as well.

In [ ]:
dMat = np.array([[ 94, 116, 104, 97, 99],
[ 92, 107, 92, 103, 104],
[115, 112, 81, 90, 90],
[ 94, 100, 90, 92, 114]])

dMat[dMat>95]

Notice that it returns a 1D array.

If you just write a condition, then it will return an array of True and False.

In [ ]:
dMat>95

### Exercise
**Mean RTs and scores**. You have two arrays of the same size.

`<RTData.py>`

In [ ]:
import numpy as np

RTMat = np.array([[111, 100,  86, 120,  91],
                  [ 92,  83, 105, 103, 112],
                  [117, 121, 124, 111, 110],
                  [111,  86, 113,  88, 105]])
scoreMat = np.array([[1, 0, 0, 0, 0],
                     [0, 1, 1, 0, 1],
                     [0, 1, 1, 0, 0],
                     [0, 0, 1, 1, 0]])

where **`RTMat`** corresponds to the response times (RT) in ms and **`scoreMat`**
corresponds to the scores from the same experiment.

1. **Mean RT**. Calculate the mean RT for observations with score =0. Do the same for observations with score = 1.<br>
      ***Hint:*** *You can use the **`mean()`** method for an array*. 
    
2. **Mean score**. Calculate the mean score for observations with `RT`>100ms.

# Image data
<hr style="height:1px;border:none" />
## Data sets

Now that we know how to handle array data in Python, we can take a look at some image data. Brain image data are often saved as 3D arrays (e.g., T1-weighted structural MRI) or 4D arrays (e.g., fMRI time series). For this exercise (and for some future exercises), I would like you to download two publicly available fMRI data sets, available on OpenNeuro.org. *It seems like **Google Chrome** is the only web browser that lets me download these data sets.*

* Flanker task, event related [ds102](https://openneuro.org/datasets/ds000102) (~3.7GB)
* Test-retest data of motor, language, and spatial attention [ds114](https://openneuro.org/datasets/ds000114) (~4.7GB)

Both data sets should be available as zip archives (with **`.zip`** extension). First thing you want to do is to *move the files* to a desired location. For example, I have a directory called **`Data`** under my fMRI course directory, and under there. Once the zip files are at the desired location, you can extract the data sets by  unzipping the file.
```
unzip [downloaded file name.zip]
```
***Note***: This command needs to be executed on the terminal window; it is a shell command, not a Python command.

This may automatically create a new directory called **`ds000102`** or **`ds000114`** and place the contents in that directory (for Mac). Or you may need to create a separate directory for each zip file before unzipping (for Linux). In my case, I created directories called **`ds102`** and **`ds114`** for these data sets.

## Reading image data

Now let's take a look at some image data. For this exercise, we examine a subject from the `ds102` data set. I want you to select a random subject from the data set. To get a list of subjects, you can run this program. 

`<ListSubjects.py>`

In [1]:
import os

# Directory where your data set resides. This needs to be customized
#dataDir = '/home/satoru/Teaching/fMRI_Fall_2018/Data/ds102'
dataDir = '/Users/sh45474/Documents/Teaching/fMRI_Fall_2018/Data/ds102'

In [2]:
# getting a list of directory contents
dirContents = os.listdir(dataDir)
dirContents.sort()

In [3]:
# printing out a list of subjects (i.e., directories starting with sub-)
for iFile in dirContents:
    if 'sub-' in iFile:
        print(iFile)

sub-01
sub-02
sub-03
sub-04
sub-05
sub-06
sub-07
sub-08
sub-09
sub-10
sub-11
sub-12
sub-13
sub-14
sub-15
sub-16
sub-17
sub-18
sub-19
sub-20
sub-21
sub-22
sub-23
sub-24
sub-25
sub-26


*Note that you have to specify the path to the data directory, which is different likely different from mine.* 

From these subjects, I randomly pick a subject **`sub-26`**. Under that directory, there are two directories called **`anat`** (where high-resolution structural MRI data resides) and **`func`** (where 4D fMRI data file(s) resides). For the following exercises, we will read the structural MRI data and one of fMRI time series data. For the structural MRI data, it is likely that there is only one image data (with **`.nii`** extension, or a NIfTI file) in the **`anat`** directory. For the fMRI data, you can choose one of the `.nii` files randomly. In my case, under the `anat` directory:
```
sub-26_T1w.nii.gz
```
And under the `func` directory:
```
sub-26_task-flanker_run-1_bold.nii.gz
sub-26_task-flanker_run-2_bold.nii.gz
```
I will pick **`sub-26_task-flanker_run-2_bold.nii.gz`** for the exercise.

Here is an example code to read structural and functional MRI data.

`<ReadImageData.py>`

In [4]:
import os
import numpy as np
import nibabel as nib

# Directory where your data set resides. This needs to be customized
#dataDir = '/home/satoru/Teaching/fMRI_Fall_2018/Data/ds102'
dataDir = '/Users/sh45474/Documents/Teaching/fMRI_Fall_2018/Data/ds102'

In [5]:
# paths for the structural and functional MRI data. 
# NOTE that the paths are different for each user. You need to customize
f_sMRI = os.path.join(dataDir,'sub-26/anat/sub-26_T1w.nii.gz')
f_fMRI = os.path.join(dataDir,'sub-26/func/sub-26_task-flanker_run-2_bold.nii.gz')

In [ ]:
f_sMRI

In [7]:
f_fMRI

'/Users/sh45474/Documents/Teaching/fMRI_Fall_2018/Data/ds102/sub-26/func/sub-26_task-flanker_run-2_bold.nii.gz'

In [8]:
# reading in the image data arrays
# structural MRI
sMRI = nib.load(f_sMRI)
X_sMRI = sMRI.get_data()

# fMRI
fMRI = nib.load(f_fMRI)
X_fMRI = fMRI.get_data()

Here, the function **`os.path.join`** is used to combine a path to the data directory and the path to a particular image data file. 

The function **`nib.load`** is used to create an object for the image data. To actually read the image data array, you need to use the **`get_data`** method associated with an image object. 

So, were image data loaded correctly? Let's check.

In [9]:
X_sMRI.shape

(176, 256, 256)

In [10]:
X_fMRI.shape

(64, 64, 40, 146)

Here, the structural MRI is a 3D array of size 176 x 256 x 256, whereas the fMRI is a 4D array of size 64 x 64 x 40 x 164. 

### T1 image

Now, let's take a look at the T1-weighted image (or structural MRI). But before doing that, if you want to see images on Jupyter notebook, you have to run this line.

In [11]:
%matplotlib inline

`<ShowT1Image.py>`

In [34]:
import os
import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt


def show_plane(x):
    plt.imshow(np.rot90(x), cmap="gray")
    plt.gca().set_axis_off()

def show_section(xImg, section, xSlice):
    if section=='xy':
        tmpImg = xImg[:,:,xSlice]
    elif section=='xz':
        tmpImg = xImg[:,xSlice,:]
    else:
        tmpImg = xImg[xSlice,:,:]
    show_plane(tmpImg)

Here, I defined two functions. First, **`show_plane`** function displays a 2D array as a gray-scale image. This function is called by **`show_section`** function. Depending on the parameters provided, `show_section` can produce a section from the 3D T1 image sliced at a particular plane. There are 3 different ways to slice the brain:
  * **Axial** section - (xy-plane)
  * **Coronal** section - (xz-plane)
  * **Sagittal** section - (yz-plane)
By specifying the parameter **`section`**, you can switch between different sections in this function.

Now, let's load the image data.

In [31]:
# Directory where your data set resides. This needs to be customized
#dataDir = '/home/satoru/Teaching/fMRI_Fall_2018/Data/ds102'
dataDir = '/Users/sh45474/Documents/Teaching/fMRI_Fall_2018/Data/ds102'

# reading in the T1 image data array
f_sMRI = os.path.join(dataDir,'sub-26/anat/sub-26_T1w.nii.gz')
sMRI = nib.load(f_sMRI)
X_sMRI = sMRI.get_data()

And let's specify the section plane coordinates.

In [32]:
# locations (in voxels) where slicing occurs
xSlice = 85
ySlice = 110
zSlice = 140

Now different sections.

In [35]:
show_section(X_sMRI,'xy',zSlice)
plt.title('Axial section (xy-plane)')
plt.show()

In [25]:
plt.clf()

<Figure size 432x288 with 0 Axes>

In [ ]:
show_section(X_sMRI,'xz',ySlice)
plt.title('Coronal section (yz-plane)')
plt.show()

In [ ]:
show_section(X_sMRI,'yz',xSlice)
plt.title('Sagittal section (yz-plane)')
plt.show()

You can take a look at the intensity of a certain voxel. For example,

In [ ]:
X_sMRI[85,110,140]

You can calculate some basic statistics (e.g., max, min, mean, sd) of voxel intensities easily too, by using functions in `NumPy`.
* **`np.max`**: maximum
* **`np.min`**: minimum
* **`np.average`**: mean
* **`np.std`**: standard deviation

You can calculate these basic stats on the entire 3D image.

In [ ]:
np.max(X_sMRI)

In [ ]:
np.std(X_sMRI)

Note that image intensities on MRI images are on an arbitrary scale.  

You can calculate statistics on a particular section, say the sagittal section above (at `x=85`).

In [ ]:
np.average(X_sMRI[85,:,:])

Or, the average intensity across x-axis.

In [ ]:
X_maxX = np.average(X_sMRI, axis=0)
show_plane(X_maxX)

Here, the parameter **`axis=0`** indicates that the average should be calculated along the 0-th index (i.e., along the x-axis in this case). You can set **`axis=1`** or **`axis=2`** for the average across the y-axis or the z-axis, respectively.

### Exercise
1. **Maximum intensity projection**. In the 3D T1 image from above, calculate the maximum intensity along one of the axes and display the resulting image. (You may post your code, *not the resulting figure*, on Canvas discussion.)

### fMRI data

Now, let's take a look at the fMRI data. 

`<ShowfMRI.py>`

In [ ]:
import os
import numpy as np
import nibabel as nib
import matplotlib.pyplot as plt


def show_plane(x):
    plt.imshow(x, cmap="gray")
    plt.gca().set_axis_off()

def show_section(xImg, section, xSlice, t):
    if section=='xy':
        tmpImg = xImg[:,:,xSlice, t]
    elif section=='xz':
        tmpImg = xImg[:,xSlice,:, t]
    else:
        tmpImg = xImg[xSlice,:,:, t]
    show_plane(np.rot90(tmpImg))



# Directory where your data set resides. This needs to be customized
dataDir = '/home/satoru/Teaching/fMRI_Fall_2018/Data/ds102'

# reading in the fMRI data array
f_fMRI = os.path.join(dataDir,'sub-26/func/sub-26_task-flanker_run-2_bold.nii.gz')
fMRI = nib.load(f_fMRI)
X_fMRI = fMRI.get_data()

# locations (in voxels) where slicing occurs
xSlice = 32
ySlice = 28
zSlice = 22
tSlice = 0

As you recall, the data array is 4D in the fMRI data. 

In [ ]:
X_fMRI.shape

The first 3 dimensions correspond to the 3D space defined by xyz-coordinates, and the last dimension corresponds to time points. In this case, there are 146 time points. You can take a look at the time course at the particular voxel.

In [ ]:
plt.plot(np.arange(X_fMRI.shape[-1]), X_fMRI[xSlice,ySlice,zSlice,:])
plt.xlabel('Time point')
plt.ylabel('Intensity')
plt.show()

Here, the **`np.arange()`** function is the NumPy version of the **`range()`** function. Unlike the `range()` function, it can produce a series of floats as opposed to integers. The **`plt.plot`** function, as you can image from the name, plots data points on the x- and y-coordinates. This plot shows a low frequency drift, typical for fMRI. 

### Exercise
1. **Mean time course**. On your fMRI data, calculate the mean intensity at each time point. Then plot the mean intensity time series. (Post your code, not the resulting figure, on Canvas).

At each time point, the fMRI data is a 3D volume. Let's take a look at the first volume.

In [ ]:
# displaying sections
show_section(X_fMRI,'xy',zSlice, tSlice)
plt.title('Axial section (xy-plane)')
plt.show()

In [ ]:
show_section(X_fMRI,'xz',ySlice, tSlice)
plt.title('Coronal section (yz-plane)')
plt.show()

In [ ]:
show_section(X_fMRI,'yz',xSlice, tSlice)
plt.title('Sagittal section (yz-plane)')
plt.show()

### Exercise
1. **Mean and sd images**. Calculate the mean and standard deviation (sd) across time points. This should result in 3D mean and sd images. Display a section of the resulting images. (Post your code, not the resulting images, on Canvas).
2. **De-mean fMRI data**. At each time point in the fMRI data, calculate the mean intensity of all voxels at that time point. Then subtract that mean intensity from each time point. The plot the time series at a particular voxel over time. (Post your code, not the resulting images, on Canvas).

# Image viewer
<hr style="height:1px;border:none" />

To view neuroimaging data, it is easier to use an image viewer software tool, as opposed to writing a program to display. I will demonstrate 3 image viewers, FSL, SPM, and MRIcron. Pay particular attention to the following details.
* Voxel location in the voxel space or in the brain space
* Left or right
* Other details embedded in the **`.nii`** image data